// Generated by lsc from subagent-permissions.ts

datatype Option<T> = None | Some(value: T)

datatype Rule = Rule(permission: string, pattern: string, action: string)

datatype Info = Info(permission: seq<Rule>)

type Ruleset = seq<Rule>

datatype SubInput = SubInput(parentSessionPermission: seq<Rule>, parentAgent: Option<Info>, subagent: Info)

function deriveSubagentSessionPermission(input: SubInput): seq<Rule>
{
  var canTask := (exists rule :: rule in input.subagent.permission && (rule.permission == "task"));
  var canTodo := (exists rule :: rule in input.subagent.permission && (rule.permission == "todowrite"));
  var parentAgentDenies := (match (match input.parentAgent { case Some(i_oc0_val) => Option.Some(Std.Collections.Seq.Filter((rule: Rule) => ((rule.action == "deny") && (rule.permission == "edit")), i_oc0_val.permission)) case None => Option.None }) { case Some(i_oc1_val) => i_oc1_val case None => [] });
  (((parentAgentDenies + Std.Collections.Seq.Filter((rule: Rule) => ((rule.permission == "external_directory") || (rule.action == "deny")), input.parentSessionPermission)) + (if canTodo then [] else [Rule("todowrite", "*", "deny")])) + (if canTask then [] else [Rule("task", "*", "deny")]))
}

lemma deriveSubagentSessionPermission_ensures(input: SubInput)
  ensures forall j: nat :: ((j < |deriveSubagentSessionPermission(input)|) ==> !(((deriveSubagentSessionPermission(input)[j].permission == "edit") && (deriveSubagentSessionPermission(input)[j].action == "allow"))))
  ensures (match input.parentAgent { case Some(i_input_parentAgent_val) => forall i: nat :: ((i < |i_input_parentAgent_val.permission|) ==> (i_input_parentAgent_val.permission[i].action == "deny") ==> (i_input_parentAgent_val.permission[i].permission == "edit") ==> exists j: nat :: ((j < |deriveSubagentSessionPermission(input)|) && (deriveSubagentSessionPermission(input)[j] == i_input_parentAgent_val.permission[i]))) case None => true })
{
}
