// Generated by lsc from wildcard.ts

function {:axiom} match_(str: string, pattern: string): bool

method matchSequence(items: seq<string>, patterns: seq<string>) returns (res: bool)
  ensures (res ==> Matches(items, patterns))
  ensures (Matches(items, patterns) ==> res)
{
  if (|patterns| == 0) {
    return true;
  }
  var pattern := patterns[0];
  var rest := patterns[1..];
  if (pattern == "*") {
    var i_t0 := matchSequence(items, rest);
    return i_t0;
  }
  var i := 0;
  while (i < |items|)
    invariant (0 <= i)
    invariant (i <= |items|)
    invariant forall j: nat :: ((j < i) ==> !((match_(items[j], pattern) && Matches(items[(j + 1)..], rest))))
    decreases (|items| - i)
  {
    var i_t1 := matchSequence(items[(i + 1)..], rest);
    if (match_(items[i], pattern) && i_t1) {
      return true;
    }
    i := (i + 1);
  }
  return false;
}
