// Generated by lsc from evaluate.ts

datatype Option<T> = None | Some(value: T)

function SeqFindLast<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFindLast(s, p).Some? ==> p(SeqFindLast(s, p).value)
  ensures SeqFindLast(s, p).Some? ==> SeqFindLast(s, p).value in s
  ensures SeqFindLast(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFindLast(s, p).value && p(s[i]) &&
                     (forall j: nat :: i < j < |s| ==> !p(s[j]))
  ensures SeqFindLast(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[|s|-1]) then Some(s[|s|-1])
  else SeqFindLast(s[..|s|-1], p)
}

function SeqFlatten<T>(s: seq<seq<T>>): seq<T>
  decreases |s|
{
  if |s| == 0 then []
  else s[0] + SeqFlatten(s[1..])
}

function {:axiom} Wildcard_match(str: string, pattern: string): bool

datatype Rule = Rule(permission: string, pattern: string, action: string)

function evaluate(permission: string, pattern: string, rulesets: seq<seq<Rule>>): Rule
{
  var rules := SeqFlatten(rulesets);
  var match_ := SeqFindLast(rules, (rule: Rule) => (Wildcard_match(permission, rule.permission) && Wildcard_match(pattern, rule.pattern)));
  match match_ {
    case Some(i_oc0_val) =>
      i_oc0_val
    case None =>
      Rule(permission, "*", "ask")
  }
}

lemma evaluate_ensures(permission: string, pattern: string, rulesets: seq<seq<Rule>>)
  ensures ((forall i: nat :: ((i < |SeqFlatten(rulesets)|) ==> !((Wildcard_match(permission, SeqFlatten(rulesets)[i].permission) && Wildcard_match(pattern, SeqFlatten(rulesets)[i].pattern))))) ==> (((evaluate(permission, pattern, rulesets).permission == permission) && (evaluate(permission, pattern, rulesets).pattern == "*")) && (evaluate(permission, pattern, rulesets).action == "ask")))
  ensures ((exists j: nat :: (((j < |SeqFlatten(rulesets)|) && Wildcard_match(permission, SeqFlatten(rulesets)[j].permission)) && Wildcard_match(pattern, SeqFlatten(rulesets)[j].pattern))) ==> exists k: nat :: (((((k < |SeqFlatten(rulesets)|) && (evaluate(permission, pattern, rulesets) == SeqFlatten(rulesets)[k])) && Wildcard_match(permission, evaluate(permission, pattern, rulesets).permission)) && Wildcard_match(pattern, evaluate(permission, pattern, rulesets).pattern)) && forall m: nat :: ((k < m) ==> (m < |SeqFlatten(rulesets)|) ==> !((Wildcard_match(permission, SeqFlatten(rulesets)[m].permission) && Wildcard_match(pattern, SeqFlatten(rulesets)[m].pattern))))))
{
}
