// Generated by lsc from index.ts

datatype Option<T> = None | Some(value: T)

function SeqFindLast<T>(s: seq<T>, p: T -> bool): Option<T>
  ensures SeqFindLast(s, p).Some? ==> p(SeqFindLast(s, p).value)
  ensures SeqFindLast(s, p).Some? ==> SeqFindLast(s, p).value in s
  ensures SeqFindLast(s, p).Some? ==>
    exists i: nat :: i < |s| && s[i] == SeqFindLast(s, p).value && p(s[i]) &&
                     (forall j: nat :: i < j < |s| ==> !p(s[j]))
  ensures SeqFindLast(s, p).None? ==> forall i :: 0 <= i < |s| ==> !p(s[i])
  decreases |s|
{
  if |s| == 0 then None
  else if p(s[|s|-1]) then Some(s[|s|-1])
  else SeqFindLast(s[..|s|-1], p)
}

function {:axiom} Wildcard_match(str: string, pattern: string): bool

datatype Rule = Rule(permission: string, pattern: string, action: string)

type Ruleset = seq<Rule>

// LemmaScript: skipped Action

// LemmaScript: skipped Rule

// LemmaScript: skipped Ruleset

const EDIT_TOOLS: seq<string> := ["edit", "write", "apply_patch"]

method disabled(tools: seq<string>, ruleset: seq<Rule>) returns (res: set<string>)
  ensures forall t :: ((t in res) ==> (t in tools))
  ensures forall i: nat :: ((i < |tools|) ==> (tools[i] in res) ==> exists k: nat :: (((((k < |ruleset|) && Wildcard_match((if (tools[i] in EDIT_TOOLS) then "edit" else tools[i]), ruleset[k].permission)) && (ruleset[k].pattern == "*")) && (ruleset[k].action == "deny")) && forall m: nat :: ((k < m) ==> (m < |ruleset|) ==> !(Wildcard_match((if (tools[i] in EDIT_TOOLS) then "edit" else tools[i]), ruleset[m].permission)))))
  ensures forall i: nat :: ((i < |tools|) ==> (exists k: nat :: (((((k < |ruleset|) && Wildcard_match((if (tools[i] in EDIT_TOOLS) then "edit" else tools[i]), ruleset[k].permission)) && (ruleset[k].pattern == "*")) && (ruleset[k].action == "deny")) && forall m: nat :: ((k < m) ==> (m < |ruleset|) ==> !(Wildcard_match((if (tools[i] in EDIT_TOOLS) then "edit" else tools[i]), ruleset[m].permission))))) ==> (tools[i] in res))
{
  var result: set<string> := {};
  var i_tool_idx := 0;
  while i_tool_idx < |tools|
    invariant (i_tool_idx <= |tools|)
    invariant forall t :: ((t in result) ==> exists j: nat :: ((j < i_tool_idx) && (tools[j] == t)))
    invariant forall j: nat :: ((j < i_tool_idx) ==> (tools[j] in result) ==> exists k: nat :: (((((k < |ruleset|) && Wildcard_match((if (tools[j] in EDIT_TOOLS) then "edit" else tools[j]), ruleset[k].permission)) && (ruleset[k].pattern == "*")) && (ruleset[k].action == "deny")) && forall m: nat :: ((k < m) ==> (m < |ruleset|) ==> !(Wildcard_match((if (tools[j] in EDIT_TOOLS) then "edit" else tools[j]), ruleset[m].permission)))))
    invariant forall j: nat :: ((j < i_tool_idx) ==> (exists k: nat :: (((((k < |ruleset|) && Wildcard_match((if (tools[j] in EDIT_TOOLS) then "edit" else tools[j]), ruleset[k].permission)) && (ruleset[k].pattern == "*")) && (ruleset[k].action == "deny")) && forall m: nat :: ((k < m) ==> (m < |ruleset|) ==> !(Wildcard_match((if (tools[j] in EDIT_TOOLS) then "edit" else tools[j]), ruleset[m].permission))))) ==> (tools[j] in result))
  {
    var tool := tools[i_tool_idx];
    var permission := (if (tool in EDIT_TOOLS) then "edit" else tool);
    var rule := SeqFindLast(ruleset, (rule: Rule) => Wildcard_match(permission, rule.permission));
    match rule {
      case Some(i_rule_val) =>
        if ((i_rule_val.pattern == "*") && (i_rule_val.action == "deny")) {
          result := (result + {tool});
        }
      case None =>

    }
    i_tool_idx := i_tool_idx + 1;
  }
  return result;
}
